
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.alientrap.nexuiz.demotool.Demo;
import org.alientrap.nexuiz.demotool.DemoException;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NexuizDemotool.java
 *
 * Created on Jan 28, 2010, 1:47:37 PM
 */
/**
 *
 * @author Merlijn Hofstra
 */
public class NexuizDemotool extends javax.swing.JFrame {

    private Demo currentdemo;
    private JFileChooser fc;

    /** Creates new form NexuizDemotool */
    public NexuizDemotool() {
        initComponents();
        if (System.getProperty("os.name").equals("Linux")) {
            fc = new JFileChooser(new File(System.getProperty("user.home") + "/.nexuiz/data/demos/"));
        } else {
            fc = new JFileChooser(new File(System.getProperty("user.home")));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menubar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemOpen = new javax.swing.JMenuItem();
        menuItemSave = new javax.swing.JMenuItem();
        menuItemSaveas = new javax.swing.JMenuItem();
        menuItemPreferences = new javax.swing.JMenuItem();
        menuItemQuit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuItemRename = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nexuiz Demotool");

        menuFile.setText("File");

        menuItemOpen.setText("Open demo");
        menuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOpenActionPerformed(evt);
            }
        });
        menuFile.add(menuItemOpen);

        menuItemSave.setText("Save");
        menuItemSave.setEnabled(false);
        menuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveActionPerformed(evt);
            }
        });
        menuFile.add(menuItemSave);

        menuItemSaveas.setText("Save as...");
        menuItemSaveas.setEnabled(false);
        menuItemSaveas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveasActionPerformed(evt);
            }
        });
        menuFile.add(menuItemSaveas);

        menuItemPreferences.setText("Preferences");
        menuFile.add(menuItemPreferences);

        menuItemQuit.setText("Quit");
        menuItemQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemQuitActionPerformed(evt);
            }
        });
        menuFile.add(menuItemQuit);

        menubar.add(menuFile);

        menuEdit.setText("Edit");

        menuItemRename.setText("Rename");
        menuEdit.add(menuItemRename);

        menubar.add(menuEdit);

        menuHelp.setText("Help");

        menuItemAbout.setText("About");
        menuHelp.add(menuItemAbout);

        menubar.add(menuHelp);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemQuitActionPerformed

    private void menuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOpenActionPerformed
        fc.setFileHidingEnabled(false);
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            System.out.println("Opening: " + file.getName());
            currentdemo = new Demo(file);
            try {
                currentdemo.parseDemoFile();
                menuItemSave.setEnabled(true);
                menuItemSaveas.setEnabled(true);
            } catch (IOException ex) {
                Logger.getLogger(NexuizDemotool.class.getName()).log(Level.SEVERE, null, ex);
            } catch (DemoException ex) {
                Logger.getLogger(NexuizDemotool.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_menuItemOpenActionPerformed

    private void menuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveActionPerformed
        File demofile = currentdemo.getDemofile();
        if (demofile.exists()) {
            int ow = JOptionPane.showConfirmDialog(this,
                    "This file already exists, overwrite?",
                    "File exists",
                    JOptionPane.YES_NO_OPTION);

            // 0 == yes, 1 == no, -1 == cancel
            if (ow != 0) {
                return;
            }

        }

        try {
            currentdemo.writeDemo(demofile);
        } catch (IOException ex) {
            Logger.getLogger(NexuizDemotool.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DemoException ex) {
            Logger.getLogger(NexuizDemotool.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemSaveActionPerformed

    private void menuItemSaveasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveasActionPerformed
        int returnVal = fc.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            if (file.exists()) {
                int ow = JOptionPane.showConfirmDialog(this,
                        "This file already exists, overwrite?",
                        "File exists",
                        JOptionPane.YES_NO_OPTION);

                // 0 == yes, 1 == no, -1 == cancel
                if (ow != 0) {
                    return;
                }
            }
            
            try {
                currentdemo.writeDemo(file);
            } catch (IOException ex) {
                Logger.getLogger(NexuizDemotool.class.getName()).log(Level.SEVERE, null, ex);
            } catch (DemoException ex) {
                Logger.getLogger(NexuizDemotool.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_menuItemSaveasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NexuizDemotool().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemOpen;
    private javax.swing.JMenuItem menuItemPreferences;
    private javax.swing.JMenuItem menuItemQuit;
    private javax.swing.JMenuItem menuItemRename;
    private javax.swing.JMenuItem menuItemSave;
    private javax.swing.JMenuItem menuItemSaveas;
    private javax.swing.JMenuBar menubar;
    // End of variables declaration//GEN-END:variables
}
